graph LR
  publisher[:memo:] -- Loaded by--> u1[:skull:]
  publisher -- Loaded by --> u2[:grin:]
  u1 -. No connection .-> reader[:iphone:]
  u2 -- Download --> reader

  publisher -. No Connection .-> reader
